name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # runs once per day
  workflow_dispatch: # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Uses the default GitHub token for public data
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Souhrid007
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          filename: github-metrics.svg
